### ISSUE TITLE
Create astraios data models repository

### ISSUE THREAD

**Issue by QubitPi** [paion-data/astraios#111]
## Goal

As an instantiation of the [Elide](https://github.com/paion-data/elide) API, [astraios](https://astraios.io/) requires a Data Model to run properly.

**We need to create a new repository to manage the data model separately**

## Implementation

1. [Create GitHub repo named **dental-llm-astraios-data-models**](https://docs.github.com/en/repositories/creating-and-managing-repositories/quickstart-for-repositories#create-a-repository)

   - **Owner**: `paion-data`
   - **Repository name**: `dental-llm-astraios-data-models`
   - **Description** (can be your preferred description)
   - **Public/Private**: `Private`
   - Keep other defaults and click **Create Repository**

2. Create a maven skeleton project. There are 3 approaches:

   1. One can refer to [this example project](https://github.com/QubitPi/jersey-webservice-template-jpa-data-models). This project has a [`Book` data model](https://github.com/QubitPi/jersey-webservice-template-jpa-data-models/blob/master/src/main/java/com/qubitpi/ws/jersey/template/models/Book.java). We will replace this with our own data model. Other than `Book`, everything else will be pretty much the same
   2. [Maven has a command that creates skeleton project](https://maven.apache.org/guides/getting-started/index.html#how-do-i-make-my-first-maven-project):

   ```console
   mvn -B archetype:generate -DgroupId=com.paiondata -DartifactId=dental-llm-astraios-data-models=maven-archetype-quickstart -DarchetypeVersion=1.4
   ```
   3. You can start from scratch 😉 

3. Please notify @QubitPi , who will give you details about what the data model looks like (the data model cannot be stated publicly here)

**Comment by Doom9527** [comment]
OK.
