### ISSUE TITLE
Support Spring

### ISSUE THREAD

**Issue by QubitPi** [paion-data/astraios#116]
## Goal

Keeping all functions the same, we will refactor astraios to support Spring and remove Jersey

## How to Implement

- [Elide already has an example application running in Spring](https://github.com/yahoo/elide-spring-boot-example) that we can follow.

  - Yes, simply *delete* all Jersey logics. astraios.io no longer supports Jersey. It becomes a pure Spring Boot application
  
    - The configuration, however, such as [datastore](https://github.com/paion-data/astraios/blob/master/src/main/java/com/paiondata/astraios/application/BinderFactory.java#L138), must all kept the same (because those are not related to Jersey/Spring)

  - It must support [GraphQL](https://elide.io/pages/guide/v7/11-graphql.html), because our UI talks to backend via GraphQL
  - **At the end of the day, we should have a Spring Boot application that functionally behaves *exactly the same* as the current Jersey version**

    - one exception: run Spring Boot in JAR, not WAR

- Update the [documentation](https://astraios.io/docs/intro) by replacing all Jersey contents with Spring version

**Comment by Doom9527** [comment]
Mentioned before the problem of `ResourceConfigITSpec` has been solved, but `DockerComposeITSpec` has a problem, I have not seen what happened, may be caused by the former repair

**Comment by QubitPi** [comment]
Done by https://github.com/paion-data/astraios/issues/116
