### ISSUE TITLE
Replace 'Stream.collect(Collectors.toList())' with 'Stream.toList()'

### ISSUE THREAD

**Issue by QubitPi** [paion-data/astraios#43]
There is a [code smell](https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=paion-data_astraios&open=AYqMSaB-qpE7yGoVUyZd) that can be fixed pretty quickly

**Comment by WordlessEcho** [comment]
Hi. I am interested about this issue. Could you please assign this issue to me?

**Comment by QubitPi** [comment]
I happened to take a look at `toList()`. This collects stream into a immutable list. Passing immutable object down to a component where we have little control of is risky. We will prefer the mutable version as for now. But thanks @WordlessEcho for bring this old issue onto table
